### ISSUE TITLE
 no gcc?

### ISSUE THREAD

**Issue by tnh** [jitakirin/docker-rpmbuild#2]
gcc should be on the container, no?

**Comment by jitakirin** [comment]
As far as I understand according to [fedora packaging guidelines](https://fedoraproject.org/wiki/Packaging:Guidelines#Build-Time_Dependencies_.28BuildRequires.29) this should be specified as `BuildDependency` in your package. I'd argue it's better this way as you may want gcc or clang, or go or rust or million other compilers and including them all would be impractical :smile: 

Feel free to re-open if you disagree.
